- name: variables
  hosts: localhost
  #if we are declaring variables on top level then its called play level
  vars: #variable declaration #not only declaration we will also have to access the variable
    Course: "Terraform" #defing a value
    Name: "Hk"
    Duration: "140hrs"
  tasks:
  - name: print override information #prints the info that over ridden
    vars: #Task level variable #inheritance and overriding 
      Course: "DevOps" 

    ansible.builtin.debug:
      msg: "Hi, My name is {{Name}}. I'm learning {{Course}}, Duration is {{Duration}}"  #{{}} to assign variable in ansible
      #now, we are trying to keep manisha,ansible,120hrs in a variable here
  
  - name: print information #here is going to print the info that's not over ridden
    ansible.builtin.debug:
      msg: "Hi, My name is {{Name}}. I'm learning {{Course}}, Duration is {{Duration}}"  #{{}} to assign variable in ansible
