- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print information 
    ansible.builtin.debug:
     msg: "Hi, My name is {{Name}}. I'm learning {{Course}}, Duration is {{Duration}}. Timings are {{TIMING}}"

     #need not mention inventory anywhere. it will go find it by itself.