#int,float,double,arraylist,map,boolean
#In ansible : number, string,list, map

- name: data types
  hosts: localhost
  vars:
    Course: Devops with AWS #string
    Tools: #if it start with hi-fun its list
    - Linux
    - Shell
    - Ansible
    Experience: #map or dictionary
      Devops: 3 #number
      AWS: 2
      Docker: 1
    RealProject: true #boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools coverred: {{Tools}}, Experience is {{Experience}},is real project: {{RealProject}}"


